- hosts: webservers

  tasks:

    - name: Pull docker image
      docker_image:
        name: "{{image_name}}:latest"
        source: pull

    - name: Run docker container
      docker_container:
        name: "{{container_name}}"
        image: "{{image_name}}"
        state: started
        pull: true
        ports:
        - "8000:8000"